export const FETCH_ALL_IMAGES = 'FETCH_ALL_IMAGES';
export const FETCH_ALL_IMAGES_FAILED = 'FETCH_ALL_IMAGES_FAILED';
export const FETCH_ALL_IMAGES_SUCCESS = 'FETCH_ALL_IMAGES_SUCCESS';
export const SEARCH_CRITERIA = 'SEARCH_CRITERIA';